name: CI
on: [push, pull_request]
jobs:
  build-macos:
    name: macOS Build
    runs-on: macOS-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Select Latest Xcode
        run: |
          set -xe
          sw_vers
          ls -d /Applications/Xcode*.app
          sudo xcode-select --switch `ls -d /Applications/Xcode*.app | sort -Vr | head -n1`
          xcode-select -p
          xcodebuild -version
          xcodebuild -showsdks
      - run: brew update && brew install qt5
      - name: Build
        working-directory: ./Software
        run: |
          export QTDIR=/usr/local/opt/qt
          export PATH=$PATH:$QTDIR/bin
          qmake -r
          make
          macdeployqt bin/Prismatik.app -dmg 
          
      - name: Check Package
        run: |
          set -xe
          VERSION=`cat Software/VERSION`
          PKG_PATH="Software/bin/Prismatik.dmg"
          PKG_NAME="Prismatik_${VERSION}.dmg"
          echo "PKG_PATH=$PKG_PATH" >> $GITHUB_ENV
          echo "PKG_NAME=$PKG_NAME" >> $GITHUB_ENV
      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PKG_NAME }}
          path: ${{ env.PKG_PATH }}