name: build-ubuntu
on: [push, pull_request]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: sudo apt-get install qt5-default libqt5serialport5-dev build-essential libgtk2.0-dev libusb-1.0-0-dev libudev-dev libnotify-dev qttools5-dev-tools libappindicator-dev openssl libpulse-dev libfftw3-dev hashdeep
      - run: qmake -v
      - run: qmake -r && make
        working-directory: ./Software
      - run: scripts/linux/prepare_installer.sh
        working-directory: ./Software
      - run: ./build-deb.sh amd64
        working-directory: ./Software/dist_linux
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: Software/dist_linux/*.deb
  build-fw-ubuntu:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: sudo apt-get install gcc-avr avr-libc build-essential
      - run: ./build_batch.sh
        working-directory: ./Firmware
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: Firmware/hex/*