name: CI
on: [push, pull_request]
jobs:
  build-ubuntu:
    name: Ubuntu Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install qt5-default libqt5serialport5-dev build-essential libgtk2.0-dev libusb-1.0-0-dev libudev-dev libnotify-dev qttools5-dev-tools libappindicator-dev openssl libpulse-dev libfftw3-dev hashdeep
      - run: qmake -r && make
        working-directory: ./Software
      - run: scripts/linux/prepare_installer.sh
        working-directory: ./Software
      - run: ./build-deb.sh amd64
        working-directory: ./Software/dist_linux
      - name: Check Package
        run: |
          set -xe
          PKG_PATH=$(ls Software/dist_linux/*.deb)
          echo "PKG_PATH=$PKG_PATH" >> $GITHUB_ENV
          echo "PKG_NAME=$(basename $PKG_PATH | sed 's#amd64#${{ matrix.os }}_amd64#; s# ##')" >> $GITHUB_ENV
      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PKG_NAME }}
          path: ${{ env.PKG_PATH }}
      - name: 
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: Software/dist_linux/*.deb
  build-fw:
    name: Firmware Build
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: sudo apt-get install gcc-avr avr-libc build-essential
      - run: ./build_batch.sh
        working-directory: ./Firmware
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: Firmware/hex/*